apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudflare-tunnel-ingress-controller

helmGlobals:
  chartHome: helm

helmCharts:
  - name: cloudflare-tunnel-ingress-controller
    releaseName: cloudflare-tunnel-ingress-controller
    namespace: cloudflare-tunnel-ingress-controller
    valuesFile: myvalues.yaml

resources:
  - namespace.yaml

# generators:
#   - secrets-generator.yaml
# Secret applied manually
