apiVersion: apps/v1
kind: Deployment
metadata:
  name: starlink-exporter
  labels:
    app: starlink-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starlink-exporter
  template:
    metadata:
      labels:
        app: starlink-exporter
    spec:
      containers:
        - name: starlink-exporter
          image: ghcr.io/danopstech/starlink_exporter:latest
          args:
            - --address=192.168.1.1:9200
            - --port=9817
          ports:
            - name: metrics
              containerPort: 9817
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
          livenessProbe:
            httpGet:
              path: /metrics
              port: 9817
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /metrics
              port: 9817
            initialDelaySeconds: 5
            periodSeconds: 10
      restartPolicy: Always
