apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qbittorrent

resources:
  - namespace.yaml
  - pvcs.yaml

generators:
  - secrets-generator.yaml

patches:
  - target:
      kind: Deployment
      name: qbittorrent
    path: patches/gluetun-secrets-dns.yaml

helmCharts:
  - name: qbittorrent
    repo: https://charts.alekc.dev
    version: 0.4.0
    releaseName: qbittorrent
    namespace: qbittorrent
    valuesFile: values.yaml
