apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trivy-system

resources:
  - namespace.yaml

helmCharts:
  - name: trivy-operator
    repo: https://aquasecurity.github.io/helm-charts/
    version: 0.31.0
    releaseName: trivy-operator
    namespace: trivy-system
    valuesFile: values.yaml
    includeCRDs: true
