apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tracearr

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - ingress.yaml

generators:
  - secrets-generator.yaml
