apiVersion: v1
kind: Service
metadata:
  name: maintainerr
  namespace: maintainerr
spec:
  selector:
    app: maintainerr
  ports:
    - port: 80
      targetPort: 6246
      protocol: TCP
      name: http
  type: ClusterIP
