apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - resources/starlink-exporter-deployment.yaml
  - resources/starlink-exporter-service.yaml
  - resources/starlink-exporter-servicemonitor.yaml
