apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: falco

resources:
  - namespace.yaml

generators:
  - secrets-generator.yaml

helmCharts:
  - name: falco
    repo: https://falcosecurity.github.io/charts
    version: 8.0.0
    releaseName: falco
    namespace: falco
    valuesFile: values.yaml
    includeCRDs: true
  - name: falcosidekick
    repo: https://falcosecurity.github.io/charts
    version: 0.12.1
    releaseName: falcosidekick
    namespace: falco
    valuesFile: values-sidekick.yaml
