apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: piper

resources:
  - namespace.yaml

helmCharts:
  - name: wyoming-piper
    repo: https://gitlab.com/api/v4/projects/62293226/packages/helm/stable
    version: 0.1.3
    releaseName: wyoming-piper
    namespace: piper
    valuesFile: values.yaml
