apiVersion: ENC[AES256_GCM,data:Gz0=,iv:856pLF3MT5AdmtmWRK6DbZ9xIoMCLKkACZ/g1afEhso=,tag:FQ+tGW3PzeqjxMR+hQ305Q==,type:str]
kind: ENC[AES256_GCM,data:3M+xl5gi,iv:WoVtYG1pGPmlS2M9jlGy8dAMNANZSXaRFMURCCVTu+M=,tag:3EGkEjTDP3iH8kI+1ZHsMg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:0PxDe3j/SvCzUIUiYR8LcHOD+QO/mwdt5HY1NMdnZLCmjHBW,iv:zYTO1zgMnbq1TzC2rTW6j+p+Go371OzY12FRQ+ETGUY=,tag:ln6AorVF4kEw1cP7VfVI0A==,type:str]
    namespace: ENC[AES256_GCM,data:cKjPO7fg3w==,iv:DeDyGyaZ/t5iMZl4cem9uEOm7vZKItkyp/i2bbqXXwc=,tag:5/eo/SaNhbjtItHP2UBDEw==,type:str]
    labels:
        app.kubernetes.io/instance: ENC[AES256_GCM,data:qSZw0wyU/g==,iv:ooniKPMTHMlKE1Qf7+HoreydhXNHaYQdA01GihMi2Lg=,tag:qjG220GLk0y4UhBLFaLiPA==,type:str]
        app.kubernetes.io/managed-by: ENC[AES256_GCM,data:wcckVA==,iv:Qw/+tv64gyeWPRUONv52cMYMein92uriV/8NsqB0ivk=,tag:Xnf/jd0ocAp7wL718mLUlw==,type:str]
        app.kubernetes.io/name: ENC[AES256_GCM,data:NYERzpkpJE+EWJ2N5rg=,iv:7MbjuIfmu95Ms80gupBb1Ju7WTrzhdhUdtrG1l3bZ1g=,tag:0rSqu60RGowg8vR+Fy9Cug==,type:str]
type: ENC[AES256_GCM,data:yEgBLJor,iv:zjJl+aCACdI0qGjsf7lAZFKQVvmUrm7IzehEwX/lSBY=,tag:amXyYT3/+iZUQS8RpTFOQg==,type:str]
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:5Aa06Cy0lDFDVtAjnzNdek8FNStzwHAk9Fz9SnsJ9POsvQODoLLD4OHwF1Cg+9ePalx6AopUG4J4991p9i6LOanRyvFL3UvAA/d0WEnnZK5REvQQHfPhZ7dC7mjj/DM7XsOWTl7Fqmsytj9+3XYi4VzM4+RjJjyghjqTqRJZLj56DLy/TCVP6K4FC1UTkLyx1vIVMwZCShgOCRDVKbK/fF3SdETy5FmHl2mlFy/HRN315L6C8NPmytqPS/xVeburr7RzpZajsklAOJnNLBn8sLL1ogJFJPmIjftwiR4dJ4qq+YgLBqLJesEQ5otU9rvC4FfMEa1/MOv5ZiPZE2uo8++CZs422o/EDKZhIjXFwcbsGH07WA7SiQrfrYWDdgTLZXz/np0cY2mWvfaywPoJ50W4vOWkm5HF7cL8ea9/CUm4wNjKcR7u5K5NNT4FGyCsUFNdJzlqHsFZhYR09B3xS1jUAvl/17lwx3fEtrXS8OWDSVDGPA9c32VqgBCCsgUH5vphZR4/fdDNihz2hvVb/TnvhH0C8JQVcI96RVvu32fvPSxgYR2IsiyAP3mo5VDdiXVfUZXiWO4jEuYVEkL0BLnKYTPsg6b46vBmCDflmAzRGPCLUe/uABU0dIEokIvFapX4vxjZ5NGmh3t5tfuiRJBOfoIx//SIWSyUmdrHFXlrHrbXZDef/Y0UkaqhxfDFjUQdyCF+kptGxszWbYKKAUpG2n6xJg5akt6DYqr8JX63vBDpb7+oLNgX8iwTFjnc4olkPP0mHf9P5gcUHjJjHt4mxiuu5hi5Bj8jvK5x5aaZdjE7GyEKgPytCHg6nhaxkAWbYLq/7Hcb/3TBFKFe/wCsMqOnQ48PzT+gFo5+OI2z0tKFNgcdKWzNltYktPZimaCuUnY6Bd/MyMrfAuGZKAkBnoqv0rdQ05Ps610ZBMK5Ny7yVlf2DRAvGpj8cR5EvtzqAkJQKDCWOEs=,iv:wX5j92wGV1iz/zqECujy+tENlN3cCrpEuwmxrUfpwlg=,tag:Odxgr/XhIPw2CSmKhHfDpA==,type:str]
sops:
    lastmodified: "2026-01-07T02:50:41Z"
    mac: ENC[AES256_GCM,data:rs4KhTsgpL6N2rYo3YhR9nlaiEHSWdqrIOem5s60cJC302wxu83DP+JiKSShUgVyRH8y2Uydo72OYBxPoXGwWJz7N3IqX91F3Tzjkk4YArcFJkckAv054ELeAgZz6uivGVMVIqo4W5BXwWIwrEUlFBuu+1JoE8QT4hkphLTG3Ys=,iv:oqBKkIf1SkBR8Xf+V6o4P+3FD/sPIufMdfZOQRL3OdE=,tag:Sh3KHGv/Ncagk8g1LKgb+w==,type:str]
    pgp:
        - created_at: "2026-01-07T02:50:41Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0AQ//VlLyzqtlCczy/Lj9g88jybE6tnkogAUTRY+0txfe/fwi
            Y8YNd7bbiInkDid4hQg1LQGGdYobsKj5OwqZBw+YMt+/O5Cj62H9wdPkUYEpEXdv
            tEXp1yGaYkOcVueUak8Y+ptWlSYwXBSuSTVhvpWzpSXDMl2d/PYQlmPmpRMW+T6i
            mpVAnO1/fNybFT1d/p3NNRsAAFGKyJxQsRluZ6JGt3Tj7sctSxBkDSF1S8Did95u
            dpUBqr3/09CyTbKyz5c0R4zXJwsGCm2zyfJ1b0HmLpgsw0IXDts7fjhlwpTJiV+G
            BsGGEwomP2iTSXAHU1oA4HmmcvztHf/yyJkNKiDf2yeI+lS+scoCfe136nJZcZIM
            ZM1gWGVqN5FJ4ZP2AONpEKkDxTJJwOUyKW8YX7Gtv9IZXC2XW1JGb+bQxIYjjyKQ
            p5YZitJgX999zJFm4DAcEK8yYUiX9chPRWy25YHYGzgfJDa8HAIj6BpxlU1egfOK
            1bWeZukpRXUU86owPClygPlA5r1b46Lr+mckuoTIHA5pNfgeTEetM2TKcGkBUQcK
            2k3QbAlF9ooeAp49Q+NtxEs4nAgueExEsBVX+4NEQJYUbTJ8+0sMddw9wTgDLHbY
            lmRmTq7v4MJsOUnYAEP3wEPKx+LQGXDqkEB1qFeSMsBVZwFhSvyTV/5m+WGy9G3U
            ZgEJAhD5AXr//VuO78I+9pnz+TV90bITdaNz/CcNrbrgaSMvG4JKQ3WuBi2sUeS4
            ACKmlPihWzx5a1uaz3yTAH6yTEdJC7hHCpq30XtmS2rgNozbeoT+EX9PpS9Bkx9i
            baiA0rrDdw==
            =VNkl
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
