apiVersion: ENC[AES256_GCM,data:b8c=,iv:JcCs6pwpQgLFwyq0nGFxhWXr+5wj8I6zBybj5Uc+mU0=,tag:3rrdUavVevKITa2BKR4K3A==,type:str]
kind: ENC[AES256_GCM,data:T17jRy0C,iv:vIYD7alnDLbeYMmhdW7P3osAXx94xrQNIX/CiM3QH/U=,tag:kSUaUF0sBLUgaVuQAUGjCQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:TmcWBYP/Xmf3TTey2OEIupBYDsldlu3e3vOusOa0GzGb6m0u,iv:JKvTM4mYevYcQxbekFGG5zaV6JYylHsXVWmbDVIwJBE=,tag:LktshifTaQoUqW5dhtNNhw==,type:str]
    namespace: ENC[AES256_GCM,data:tMIA6GcTUA==,iv:iPYqWBc7Qip2xhOkkkahj1xCUNIz7pTzZr/G+pU8QAg=,tag:sbFC7O4Y2HzfwtbsvdxzEQ==,type:str]
    labels:
        app.kubernetes.io/instance: ENC[AES256_GCM,data:CKOyER6HAA==,iv:tK4AxNB5VvGRdCyunDaFOSjQPRebp9KRkVQYh315Wvc=,tag:fZTnqenuhl5hrrt42aZEeQ==,type:str]
        app.kubernetes.io/managed-by: ENC[AES256_GCM,data:QE4i2g==,iv:RBPWUgsguMyhudVUSevCM46wNLY7oqgjR1f1QVIOIUs=,tag:AznRzVlGVfgb6TKKJvjKwg==,type:str]
        app.kubernetes.io/name: ENC[AES256_GCM,data:aWTWm4XdZ5/csYdBiSs=,iv:KMDILezwkN2GufQxW2oyl2ws27u8LrY9rB2DBWcGfZQ=,tag:iuSf2tsjEQGFytStjThanw==,type:str]
type: ENC[AES256_GCM,data:3hkIR25R,iv:0f0jS9kyRF62o+7Kwl2qSpWGpkl1XfxjvuftzFwtHM0=,tag:tp7PT0uvp4NC41lwWGSdrA==,type:str]
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:55kMXh2i27an1jAhPd+2ed7PdDe9Df9qdwQsvRE9XAt29OspGecVA+T+soLsYE2la1gqXtbNn0rNNgaLkDP9Wm5U025oUatiaGLOsFEphbaRDrCkS8FMYF6Ui0ENUMxnme/gkytk2YpRa4Hg+/8PGcApFnTsWj8f6e2biB/MJ7qYAYz8lTtXcXFbzfO4MlquUSdez3f/0Hm9oRxRUQBD48bhik6p3P5a9XtoSTBG06azvcyqJ9urLrP+BVgEpvxa32+QOzZXqNU3Hb7k2P21wNYF/hZjc8XuGG3wn8ZHWOqWMn4bHYzH7Su/x46Ta56MqS0R21s024zJIvk+v4n84SK9Zq7taEgT8tRfd4CvcF9xgqXd6+vRHYQE4KyYDHfrHOihthSaTbpaVVtsc7d5l+vjMzY2jAVuhzIhgD5EtfBIMxlVRV0+CU3wogvKBJPseXZ6T2nJM1VOLECIh5gc9BgESgD41lBgwjBxMVFT7ZdLmpROmgZ4FSPJTeBg5B1SdJ/ZsVmYUMaXXbDcqQSzGL4fQI166uGz2/DfIa63OSIOMZ9I4aL0EmqFtYCzvUTj7ZN5/pcRRuSVdQ5sLSmS123mfv+wePXOG92V/7aNanuf9R2xfw7/tmNuzu21O3wzuyc2Auj8BTx90ulP7JpsKOOAtDAJPKaKoAMD6LA/VcF0mmlM+2VqLlALgBwAw2p+ErbCI52YjYFnNu3FkzPF1ALT63x5a8EWM15/XcJ+ltvPQF9t3VWLFgi5qDQuIlaDZgkw1ShL3Ekbwbj3Qboi41H0HAYGGowLUhzyMMUxge13zitDfc7sEPJgmrpSsi1QzSkuGRNSNqtABkK3YSAsT30ew1WcCVllQOiQ7KVN4C9M76UgHXeNQ/kvTgA8e7+Jchobr9by3hVw/iSuW2JImgfHmnlVh0ahgt2czn4qHfFO9um/JxKkB8MbIRfJWyEbKJ0KV3lb8s/WEw==,iv:djm1t00tNV5jl5Yr3Ad6uDOCt+dQ8kaPsClO5fu6Nic=,tag:pXvGy0ReoM7Gi9sJAhZHzA==,type:str]
sops:
    lastmodified: "2026-01-07T03:01:15Z"
    mac: ENC[AES256_GCM,data:FNtXHLmKZc8ecJokFL/qKlt/euBOJViwhZoM+FRMsf/Vev0cvocRfYNpMHia74kGNcn7y+bvwigWL1ERAQwQEzXHM31m7ja+EC9muuUKorhqgDx1Poy+yiPGVRnoKrQasvLhuSkLHziwESaxa180C9IN78+m7rzSZU6Yp7gl9r4=,iv:Wpd+mXmWhXgEc1GTCABNrMH+zQnUCRJOsRzjIiMIAJ4=,tag:hYJ7VQ6nv5s+4y9pINiQPQ==,type:str]
    pgp:
        - created_at: "2026-01-07T03:01:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAyWa2KFcaQZ0AQ/8DnOZAACSSid4czyz+Dgpp2k2RUFj9A7nPJUs3J3hX16E
            rlJHfV5dapvnkHMfUwfzf2AAWp+eS9OFrGaUahPeZ2VDLncPJTt2T26i7JL+S2jE
            lcNBelx+dqPDsxYVRBTYythW7LoC2p5veRjlkLLe1nkhtEvOVuQ682RjC3VpQ+zA
            fTTxDLk1oCGFYiIOaexRSTW+u1Y0HQZpdeXwWTFCJoKuGgeZmXfmGABTHnHHxs13
            uLS6oE3p9rksTJb2tXBQTIvE0rAz9bVwBDvVQ1f1ae57A0O6sMZQpzmYHdFFhUfQ
            WgNza3/cSAV5Wn09ncT22q2z5xOao05DXwshOH80uXm3E7+m7aJpbLpbzI7mUqEU
            feEcrsP+uOPuznvLvjK5QyKSa6Lq98zEc5HuNoNSlAZz3HDC/UqxjEBGdpdLbxhf
            c5cylmE+OkQrkZHkdMObSw4cUSslqsFdgvrx6c21GcJnxzU4E/o1BvfOEWuCfm11
            N05TH4Nx+Xzyl9A8YUYi9R5Zyf23e/YqwFCFNvl9P/ruAxN0dz89U/FEv8vQQSj7
            O/iJmq0iL/Q3b8kuJ1j2H+peRQkb2VPKZkqHO79yL2Hw2Gs/l8WaJ5iRg/utMjW1
            VmmnP4dg3WNt9QkAidR7fWJ+lxUmbisZuRSdlQ6OuH8q2gRu1UiwWFWwXHoVOAnU
            aAEJAhCblFPydD5oNWKnIFJ5Cl1B8kR2jE9F1SDW2H7jt5IqAJX5J59cEhF+UQEU
            9vjT6/JsXqo8syIsy5KKF7/ScWY6GJJiNt8M7W+f0HJNbOoSrXIR7rnBou960yEy
            NjATSdGQDS7S
            =HNuN
            -----END PGP MESSAGE-----
          fp: 9D032060B05603F790D340F98B60D1C1CF8E1A50
    unencrypted_suffix: _unencrypted
    version: 3.11.0
