apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - resources/local-storage.yaml

helmCharts:
  - name: victoria-logs-single
    repo: https://victoriametrics.github.io/helm-charts
    version: 0.11.23
    releaseName: victoria-logs
    namespace: monitoring
    valuesFile: values-logs.yaml
  - name: victoria-logs-collector
    repo: https://victoriametrics.github.io/helm-charts
    version: 0.2.4
    releaseName: victoria-logs-collector
    namespace: monitoring
    valuesFile: values-collector.yaml
