# Public ingress for jellyfin.asandov.com via Cloudflare Tunnel
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin-cloudflare
  namespace: media-v2
spec:
  ingressClassName: cloudflare-tunnel
  rules:
  - host: jellyfin.asandov.com
    http:
      paths:
      - backend:
          service:
            name: external-truenas
            port:
              number: 30013
        path: /
        pathType: Prefix
